workflows:
  default:
    name: Default Workflow
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Clean and create Android folder
        script: |
          rm -rf android
          flutter clean
          flutter create --platforms=android .
      - name: Build APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/apk/debug/*.apk
