name: us_app
description: A private two-person social app
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_database: ^10.3.9
  camera: ^0.10.5+5
  image_picker: ^1.0.7
  video_player: ^2.8.1
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.2
  uuid: ^4.2.1
  intl: ^0.18.1
  path_provider: ^2.1.1
  shimmer: ^3.0.0
  local_auth: ^2.1.7
  flutter_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
